config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :orders, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post 'order/create'

  #
  # get 'sessions/new'
  #
  # get    '/cart',   to: 'sessions#new'
  # post   '/cart',   to: 'sessions#create'
  # delete '/empty',  to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resource :comments
  resources :products
  resource :cart
  resources :order_items, only: [:create, :update, :destroy]
  root to: 'products#index'
# get 'posts' => 'posts#index'
# get 'posts' => 'posts#show'
  resources :posts
get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :taggings
    has_many :products, through: :taggings
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :set_default_values

  private
    def set_default_values
      if self[:status].nil?
        self[:status] = "PENDING"
      end
    end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  def find_product(pid)
    if self.product.exist(pid)
      product.id
    else
      errors.add(:product, "can not find such product")
    end
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/post.rb
class Post
  # self.site = "https://jsonplaceholder.typicode.com/posts"
  include ActiveModel::Serializers::JSON
  # require 'CallApiService'
  include ActiveModel::AttributeMethods
  require 'ostruct'

  attr_accessor :userid, :id, :title, :body

  def attributes=(hash)
    hash.each do |key, value|
      send("#{key.downcase}=", value)
    end
  end

  # def attributes
  #   {userid: nil,
  #   id: nil,
  #   title: nil,
  #   body: nil
  #   }
  # end

  def self.call_with_cache(param)
    Cache.fetch "call_with_cache(#{param}" do
      response = CallApiService.init('https://jsonplaceholder.typicode.com/', 'posts').send_get(param)
      p = Post.new
      p.from_json(response.body)
    end
  end

  def self.all
    response = CallApiService.init('https://jsonplaceholder.typicode.com/', 'posts').send_get
    resource = JSON.parse(response.body)
    posts ||= []
    resource.each do |post|
      p = Post.new
      puts p
      posts << p.from_json(post.to_json)
    end
    posts
  end

  def self.show(param)
    response = CallApiService.init('https://jsonplaceholder.typicode.com/', 'posts').send_get(param)
    puts response.body
    p = Post.new
    p.from_json(response.body)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :img
  has_many :taggings
  has_many :categories, through: :taggings
  accepts_nested_attributes_for :categories, :allow_destroy => true
  validates :slug,  presence: true, uniqueness: true

  permitted = [:name, :price, :author, :price, :description, :cover,
    category_attributes: [:id]]

  has_many :order_items
  has_many :comments
  before_save :set_default
  before_validation :create_slug
  def rate(rating)
    self[:total_rating] += rating
    self[:times_rated] += 1
    set_rating
  end

  def to_param
    "#{id}-#{slug}"
  end
  
 
  private
  
  def create_slug
    self.slug = name.try(:parameterize) if slug.blank?
  end

  def set_rating
    self[:rating] = self[:total_rating] / self[:times_rated]
  end

  def set_default
    if self[:rating].nil? && self[:times_rated].nil? && self[:total_rating].nil?
      self[:rating] = 0
      self[:times_rated] = 0
      self[:total_rating] = 0
    elsif self[:times_rated].positive?
      set_rating
    end
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :category
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  def show
    @order_items = current_order
    @order_item = OrderItem.new
    @products = Product.all
  end

  def update
    current_order.update
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  helper_method :get_comment

  def create
    if Comment.new(comment_params)
      puts "got new params"
      com = Comment.new(comment_params)
      com.save
      p = Product.find(comment_params[:product_id])
      p.times_rated += 1
      p.total_rating += comment_params[:rating].to_i
      p.save
    end
  end

  private
  
  def comment_params
    params.require(:comment).permit(:product_id, :user_id, :text, :rating)
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  skip_before_action :verify_authenticity_token
  def create
    puts "CReate order"
    newo = Order.create!
    newo.total = 0
    newo.subtotal = 0
    newo.name = params[:name]
    newo.address = params[:address]
    session[:cart].each do |product_id, item|
      uprice = Product.find(product_id).price
      tprice = uprice * item['quantity'].to_i
      ii = OrderItem.new(order: newo, 'product_id': product_id, 'quantity': item['quantity'],
                         'unit_price': uprice, 'total_price': tprice)
      newo.total += 1
      newo[:subtotal] += tprice
      ii.save
    end
    if newo.save!
      session.delete(:cart)
    end

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  require "ostruct"
  require 'httparty'

  def index
    # @posts ||= []
    @posts = Post.all
    # debugger
    respond_to do |format|
      format.html
      format.json { render json: response.body }
    end
  end

  def show
    @post = Post.show(params[:id])
  end

  def create
    # Post.new(1,1, 'abc', 'xyz').to_json
    # response = HTTParty.post('https://jsonplaceholder.typicode.com/posts', form: params)
    puts response.code
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  add_breadcrumb "Product", :products_path

  def index
    @cart = session[:cart]
    @cart ||= []
    # bob = Post.first
    # jon = Jon.first
    # debugger
    # puts bob
    @categories = Category.all
    @products = Product.all
    @order_item = OrderItem.new
  end

  def show
    @category = Category.all
    @product = Product.find(params[:id])
    @order_item = OrderItem.new
    @comments = Comment.all
    @comment = Comment.new
    # # debugger
    # render :json => {
    #   :id => @product.id,
    #   :name => @product.name
    # }
    # render action: :show
    add_breadcrumb @product, product_path(@product)
    respond_to do |format|
      format.html
      format.json { render json: @product }
    end
  end
  #
  # def rate
  #   product = Product.find(params[:id])
  #   product.rate(params[:rating])
  #   product.save
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_comment(pid, uid)
    Comment.where(product_id:  pid, user_id: uid);
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/comments/create.js.erb
alert('Thanking for your review!')
location.reload();

app/views/order/create.js.erb
alert("Order submitted, redirectting to homepage")
window.location.href = "/"

app/views/posts/index.html.erb
<h3 class="text-center">Posts</h3>


<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @posts.each do |post| %>
      <p>ID: <%= post.id%>. <%= link_to post.title, post_path %> </p>

    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<h1>Post title: <%= @post.title %></h1>

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-7">
      <h4><%= link_to product.name, product %></small></h4>
    </div>
    <div class="col-xs-5">

      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1, style: 'display: width=30px' %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/products/index.html.erb
<h3 class="text-center">Products for Sale</h3>


<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @categories.each do |cate| %>
      <h3><%= cate.name%> (<%=cate.products.count%>)</h3>
      <ul>
        <% cate.products.order(:id).each do |product|%>
          <%= render "product_row", product: product, order_item: @order_item %>
        <% end %>
      </ul>
    <% end %>

  <% if false %>
    <% @products.order(:id).limit(10).each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  <%end%>
  </div>
</div>

app/views/products/show.html.erb
<h1 class="text-center">Book: <%= @product.name %></h1>
<%= image_tag url_for(@product.img), size: "300x200" if @product.img.attached?  %>
<h2>Author: <%=@product.author %></h2>
<h2>Description: </h2>
<p><%= @product.description %></p>
<!-- <div id="productRating" data-rating="<%= @product.rating %>"></div> ( Rated <%=@product.times_rated %> times) -->
<div class="productRating" data-rate-value="<%= @product.rating %>"></div> (Rated <%=@product.times_rated %> times)
<%= form_for @order_item, remote: true do |f| %>
  <h4 class="text-left">Unit Price: <span style="color: green"><%= number_to_currency @product.price %></span></h4>
  <a>Add to cart:</a>
  <div class="input-group" style="width: 300px">
    <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
    <div class="input-group-btn">
      <%= f.hidden_field :product_id, value: @product.id %>
      <%= f.submit "Add to Cart", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<% if user_signed_in? %>
  <%= form_for (@comment), remote: true do |ff| %>
    <div style="border: black; border-width: 2px" style="display: inline">
      <span>Your review and rating:</span><br/>
      <% cc = @comments.where(product_id: @product.id, user_id: current_user.id).first %>
      <% if cc%>
        <div class="myRating" style="display: inherit" data-rate-value="<%=cc.rating%>"></div>
      <% else %>
      <div class="myRating" style="display: inherit" data-rate-value=0></div>
      <% end %>
      <%= ff.text_area('text', size: "50x5", required: true, id: 'comment_text') %><br/>
      
      <%= ff.hidden_field :product_id, value: @product.id %>
      <%= ff.hidden_field :user_id, value: current_user.id %>
      <%#= ff.hidden_field 'myrating', value: 0 %>
      <input type="hidden" id="comment_rating" name="comment[rating]" value='s'/>
      <%#= ff.submit 'Submit review', class: "btn btn-primary"%>
      <input type="submit" id="btnSubmit" value="Submit review"  onclick='return submitClick();'/>
    </div>
  <%end%>
<% else %>
  <a>Login to leave a comment and rate!</a>
<% end %>
<!--  Comment section-->
<div style="border:1px solid black; width: 600px;">
  <% if !@comments.where(product_id: @product.id).empty? %>
    <h2>People's review on this product:</h2><hr/>
    <% @comments.where(product_id: @product.id).each do |comment| %>
      <div style="border: black; border-width: 3px; margin-left: 20px">
        <h3><span style="font-style: italic"><%=comment.user.email %></span> rated <%=comment.rating %> stars and said:</h3>
        <p><%=comment.text %></p>
        <hr/>
      </div>
    <% end %>
  <% end %>
</div>
<script>
  var options = {
    max_value: 5,
    step_size: 1,
    initial_value: 0,
    selected_symbol_type: 'utf8_star', // Must be a key from symbols
    cursor: 'default',
    readonly: true,
    change_once: false, // Determines if the rating can only be set once
  };
  $(".productRating").rate(options);

  <% if user_signed_in? %>
    <% if cc = @comments.where(product_id: @product.id, user_id: current_user.id).first %>  
      options.initial_value = <%= cc.rating %>
      options.readonly = true
      $('#comment_text').value = "<%= cc.text %>";
      document.getElementById('comment_text').disabled = true;
      document.getElementById('btnSubmit').style.visibility = 'hidden';
    <% else %>
      options.initial_value = 5;
      options.readonly = false;
    <% end %>
  <% end %>
  
  $(".myRating").rate(options);
  
  function submitClick(){
    if ($(".myRating").rate("getValue") == 0 || $('.comment_text').val() == "") {
      alert('pls rate and comment')
      return false
    } else {
      $('#comment_rating').val($('.myRating').rate('getValue'))
    }
  }
</script>

app/views/products/show.js.erb
alert("hh")
  var options = {
      max_value: 5,
      step_size: 1,
      initial_value: 0,
      selected_symbol_type: 'utf8_star', // Must be a key from symbols
      cursor: 'default',
      readonly: true,
      change_once: false, // Determines if the rating can only be set once
  };

  $(".productRating").rate(options);
  $(".myRating").rate(options);

  <% if user_signed_in? %>
    <% if cc = @comments.where(product_id: @product.id, user_id: current_user.id).first %>
    <% debugger %>
    
      options.initial_value = 3
      options.readonly = true
      $(".myRating").rate("setValue") = 3
      console.log("<%= cc.text %>")
      alert('<%= cc.text %>')
      $('.comment_text').value = "<%= cc.text %>";
      document.getElementById('comment_text').disabled = true;
      document.getElementById('btnSubmit').style.visibility = 'hidden';
    <% else %>
      options.initial_value = 5;
      options.readonly = false;
    <% end %>
  <% end %>
  
  // console.log("abc")
  $(".myRating").rate(options);
  $(".btnSubmit").style.visibility = 'hidden';

  $('#btnSubmit').on("click", function(ev, data){
    if( $(".myRating").rate("getValue") == 1) {
      alert('pls rate')
    }
  });
  