config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :orders, ActiveAdmin::Devise.config
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  post 'order/create'

  #
  # get 'sessions/new'
  #
  # get    '/cart',   to: 'sessions#new'
  # post   '/cart',   to: 'sessions#create'
  # delete '/empty',  to: 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users
  resource :comments
  resources :products
  resource :cart
  resources :order_items, only: [:create, :update, :destroy]
  root to: 'products#index'
# get 'posts' => 'posts#index'
# get 'posts' => 'posts#show'
  resources :posts
get '/sitemap.xml' => 'sitemaps#index', defaults: { format: 'xml' }
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :taggings
    has_many :products, through: :taggings
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :order_items
    before_save :set_default_values

  private
    def set_default_values
      if self[:status].nil?
        self[:status] = "PENDING"
      end
    end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  def find_product(pid)
    if self.product.exist(pid)
      product.id
    else
      errors.add(:product, "can not find such product")
    end
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/post.rb
class Post
  # self.site = "https://jsonplaceholder.typicode.com/posts"
  include ActiveModel::Serializers::JSON
  # require 'CallApiService'
  include ActiveModel::AttributeMethods
  require 'ostruct'

  attr_accessor :userid, :id, :title, :body

  def attributes=(hash)
    hash.each do |key, value|
      send("#{key.downcase}=", value)
    end
  end

  # def attributes
  #   {userid: nil,
  #   id: nil,
  #   title: nil,
  #   body: nil
  #   }
  # end

  def self.call_with_cache(param)
    Cache.fetch "call_with_cache(#{param}" do
      response = CallApiService.init('https://jsonplaceholder.typicode.com/', 'posts').send_get(param)
      p = Post.new
      p.from_json(response.body)
    end
  end

  def self.all
    response = CallApiService.init('https://jsonplaceholder.typicode.com/', 'posts').send_get
    resource = JSON.parse(response.body)
    posts ||= []
    resource.each do |post|
      p = Post.new
      puts p
      posts << p.from_json(post.to_json)
    end
    posts
  end

  def self.show(param)
    response = CallApiService.init('https://jsonplaceholder.typicode.com/', 'posts').send_get(param)
    puts response.body
    p = Post.new
    p.from_json(response.body)
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :img
  has_many :taggings
  has_many :categories, through: :taggings
  accepts_nested_attributes_for :categories, :allow_destroy => true
  validates :slug,  presence: true, uniqueness: true

  permitted = [:name, :price, :author, :price, :description, :cover,
    category_attributes: [:id]]

  has_many :order_items
  has_many :comments
  before_save :set_default
  before_validation :create_slug
  def rate(rating)
    self[:total_rating] += rating
    self[:times_rated] += 1
    set_rating
  end

  def to_param
    "#{id}-#{slug}"
  end
  
 
  private
  
  def create_slug
    self.slug = name.try(:parameterize) if slug.blank?
  end

  def set_rating
    self[:rating] = self[:total_rating] / self[:times_rated]
  end

  def set_default
    if self[:rating].nil? && self[:times_rated].nil? && self[:total_rating].nil?
      self[:rating] = 0
      self[:times_rated] = 0
      self[:total_rating] = 0
    elsif self[:times_rated].positive?
      set_rating
    end
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :category
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  def show
    @order_items = current_order
    @order_item = OrderItem.new
    @products = Product.all
  end

  def update
    current_order.update
  end

end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  skip_before_action :verify_authenticity_token
  def create
    puts "CReate order"
    newo = Order.create!
    newo.total = 0
    newo.subtotal = 0
    newo.name = params[:name]
    newo.address = params[:address]
    session[:cart].each do |product_id, item|
      uprice = Product.find(product_id).price
      tprice = uprice * item['quantity'].to_i
      ii = OrderItem.new(order: newo, 'product_id': product_id, 'quantity': item['quantity'],
                         'unit_price': uprice, 'total_price': tprice)
      newo.total += 1
      newo[:subtotal] += tprice
      ii.save
    end
    if newo.save!
      session.delete(:cart)
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_comment(pid, uid)
    Comment.where(product_id:  pid, user_id: uid);
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.size} Items in Cart", cart_path, class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<%= javascript_include_tag "application" %>
<%#   
  <script src="js/jquery-1.11.0.min.js"></script>
  <script src="js/bootstrap.min.js"></script> %>
  <title>Store</title>
  <%# <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <% if request.ssl? %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% else %>
    <%= stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js' %>
  <% end %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <div class="row">
      <div class="col-xs-6">
        <h1><%= link_to "My Store", root_path %></h1>
      </div>
      <div class="col-xs-5 text-right">
        <h1 class="cart-text" id="cart-text"><%= render 'layouts/cart_text' %></h1>
        <% if user_signed_in? %>
          <h2 class="user-status signed-in">Welcome, <%= current_user.email%> || <%= link_to('Logout', destroy_user_session_path, method: :delete) %></h2>
        <% else %>
          <h2 class="user-status"><%= link_to "Login", '/users/sign_in' %></h2>
        <% end %>
      </div>
      <div class="col-xs-1 text-right">

      </div>
    </div>
    <hr>
    <%= yield %>
  </div>

</body>
</html>